# Naive Bayes

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [3]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
# gaussian naive bayes - when your data follows normal distribution/gaussian
                            # distribution

In [5]:
from sklearn.naive_bayes import GaussianNB # classification

gb = GaussianNB()

gb.fit(df, iris.target)

GaussianNB()

In [6]:
gb.score(df,iris.target)

0.96

In [7]:
gb.predict([[5.1,3.5,1.4,0.2]])

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([0])

# Datasets

1. Gaussian NB
2. Multinomial NB
3. Bernoulli NB

In [9]:
docs = pd.read_table('SMSSpamCollection+(1)', 
                     header=None, 
                     names=['Class', 'SMS'])

docs.head()

  Class                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
ham_spam = docs.Class.value_counts()
ham_spam

ham     4825
spam     747
Name: Class, dtype: int64

In [11]:
docs['label'] = docs.Class.map({ 'ham':0, 'spam':1 })

docs.head()

  Class                                                SMS  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [12]:
x = docs.SMS
y = docs.label

print(x.shape)
print(y.shape)

(5572,)
(5572,)

In [13]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, random_state=101)

In [14]:
xtrain.head()

1851    Then cant get da laptop? My matric card wif ü ...
3280    Solve d Case : A Man Was Found Murdered On  &l...
3426                      True. Its easier with her here.
111              What is the plural of the noun research?
3788                          WHORE YOU ARE UNBELIEVABLE.
Name: SMS, dtype: object

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english')

In [16]:
vect.fit(xtrain)

CountVectorizer(stop_words='english')

In [17]:
vect.vocabulary_

{'da': 2027,
 'laptop': 3785,
 'matric': 4148,
 'card': 1564,
 'wif': 7049,
 'lei': 3839,
 'solve': 5926,
 'case': 1587,
 'man': 4095,
 'murdered': 4397,
 'lt': 4018,
 'decimal': 2085,
 'gt': 3068,
 'afternoon': 842,
 'wife': 7050,
 'called': 1532,
 'police': 4979,
 'questioned': 5202,
 'sir': 5818,
 'sleeping': 5853,
 'murder': 4396,
 'took': 6556,
 'place': 4920,
 'cook': 1895,
 'cooking': 1898,
 'gardener': 2898,
 'picking': 4896,
 'vegetables': 6825,
 'house': 3308,
 'maid': 4079,
 'went': 7014,
 'post': 5019,
 'office': 4620,
 'children': 1695,
 'play': 4934,
 'neighbour': 4476,
 'marriage': 4124,
 'arrested': 1031,
 'murderer': 4398,
 'immediately': 3411,
 'reply': 5383,
 'reason': 5286,
 'brilliant': 1433,
 'true': 6631,
 'easier': 2377,
 'plural': 4950,
 'noun': 4567,
 'research': 5395,
 'whore': 7040,
 'unbelievable': 6706,
 'sure': 6233,
 'parents': 4782,
 'working': 7125,
 'tuesday': 6652,
 'don': 2278,
 'really': 5281,
 'need': 4464,
 'cover': 1937,
 'story': 6122,
 'upgrdcentre': 6756,
 'orange': 4687,
 'customer': 2014,
 'claim': 1732,
 'free': 2814,
 'camera': 1545,
 'phone': 4880,
 'upgrade': 6754,
 'loyalty': 4012,
 '0207': 8,
 '153': 303,
 '9153': 714,
 'offer': 4616,
 'ends': 2447,
 '26th': 366,
 'july': 3645,
 'apply': 983,
 'opt': 4679,
 'available': 1108,
 'ne': 4454,
 'thing': 6436,
 'interesting': 3491,
 'did': 2176,
 'good': 2999,
 'birthday': 1295,
 'wrking': 7152,
 'nxt': 4590,
 'started': 6065,
 'uni': 6724,
 'today': 6524,
 'oh': 4628,
 'god': 2982,
 'home': 3268,
 'belive': 1248,
 'come': 1814,
 'yesterday': 7217,
 'going': 2988,
 'wen': 7012,
 'miss': 4264,
 'person': 4857,
 'definitely': 2101,
 'special': 5986,
 'just': 3652,
 'touch': 6580,
 'gdeve': 2915,
 'thanx': 6411,
 'puttin': 5186,
 'fone': 2761,
 'got': 3014,
 'fujitsu': 2861,
 'ibm': 3369,
 'hp': 3319,
 'toshiba': 6574,
 'lot': 3980,
 'model': 4308,
 'say': 5584,
 'sorry': 5952,
 'vikky': 6850,
 'watching': 6956,
 'olave': 4644,
 'mandara': 4102,
 'movie': 4355,
 'kano': 3670,
 'trishul': 6624,
 'theatre': 6418,
 'wit': 7080,
 'frnds': 2844,
 'know': 3731,
 'serving': 5677,
 'mean': 4168,
 'doing': 2269,
 'want': 6934,
 'pull': 5170,
 'plan': 4925,
 'spending': 5999,
 'confidence': 1859,
 'derek': 2140,
 'taylor': 6331,
 'money': 4323,
 'management': 4098,
 'win': 7058,
 'year': 7206,
 'supply': 6226,
 'cds': 1611,
 'store': 6119,
 'ur': 6762,
 'choice': 1710,
 'worth': 7137,
 '500': 528,
 'enter': 2464,
 '100': 248,
 'weekly': 6998,
 'draw': 2314,
 'txt': 6670,
 'music': 4402,
 '87066': 683,
 'ts': 6642,
 'cs': 1983,
 'www': 7170,
 'ldew': 3813,
 'com': 1808,
 'subs16': 6173,
 '1win150ppmx3': 330,
 'think': 6438,
 'honesty': 3273,
 'road': 5466,
 'bank': 1172,
 'tomorrow': 6543,
 'tough': 6582,
 'decisions': 2087,
 'make': 4087,
 'great': 3046,
 'people': 4840,
 'im': 3403,
 'arestaurant': 1009,
 'eating': 2387,
 'squid': 6038,
 '10': 247,
 '30': 415,
 'wanna': 6932,
 'dosomething': 2292,
 'late': 3792,
 'pansy': 4766,
 've': 6823,
 'living': 3924,
 'jungle': 3649,
 'years': 7207,
 'driving': 2329,
 'worried': 7131,
 'love': 3994,
 'girls': 2959,
 'wonder': 7107,
 'smiling': 5886,
 'sore': 5949,
 'sun': 6210,
 'earth': 2376,
 'send': 5656,
 'luv': 4031,
 'rays': 5255,
 'cloud': 1767,
 'river': 5465,
 'rain': 5225,
 'meet': 4183,
 'care': 1567,
 'msg': 4366,
 'gud': 3074,
 'evng': 2529,
 'horrible': 3295,
 'bf': 1274,
 'hungry': 3343,
 'hey': 3221,
 'mr': 4361,
 'sea': 5621,
 'view': 6848,
 'having': 3169,
 'couple': 1931,
 'gays': 2908,
 'games': 2889,
 'bell': 1249,
 'ya': 7192,
 'finish': 2698,
 'rs': 5497,
 'shelf': 5718,
 'buy': 1503,
 'egg': 2409,
 'elaine': 2418,
 'meeting': 4185,
 'tried': 6620,
 'contact': 1879,
 'response': 5411,
 'new': 4492,
 'nokia': 4535,
 'camcorder': 1543,
 'hit': 3240,
 '08000930705': 45,
 'delivery': 2118,
 'freemsg': 2821,
 'haven': 3165,
 'replied': 5382,
 'text': 6391,
 'randy': 5244,
 'sexy': 5690,
 'female': 2659,
 'live': 3919,
 'local': 3937,
 'hear': 3183,
 'netcollex': 4481,
 '08700621170150p': 69,
 'stop': 6111,
 'end': 2441,
 'selected': 5645,
 'stay': 6077,
 '250': 360,
 'british': 1441,
 'hotels': 3302,
 'holiday': 3263,
 'valued': 6810,
 '350': 437,
 'dial': 2168,
 '08712300220': 92,
 'national': 4444,
 'rate': 5248,
 'bx526': 1510,
 'sw73ss': 6248,
 'look': 3961,
 'amy': 923,
 'ure': 6764,
 'beautiful': 1222,
 'intelligent': 3487,
 'woman': 7102,
 'like': 3875,
 'worry': 7133,
 'lunch': 4028,
 'online': 4660,
 'latest': 3796,
 'video': 6844,
 'handset': 3123,
 '750': 612,
 'anytime': 962,
 'network': 4484,
 'mins': 4251,
 'half': 3111,
 'price': 5090,
 'line': 3888,
 'rental': 5371,
 'urgent': 6766,
 'trying': 6641,
 'todays': 6525,
 'shows': 5772,
 'won': 7104,
 '800': 631,
 'prize': 5106,
 'guaranteed': 3072,
 '09050001808': 161,
 'land': 3773,
 'm95': 4049,
 'valid12hrs': 6807,
 '1030': 255,
 'basic': 1187,
 'yoga': 7223,
 'course': 1934,
 'bugis': 1477,
 'pilates': 4906,
 'intro': 3497,
 'sat': 5568,
 'tell': 6360,
 'time': 6487,
 'girl': 2956,
 'hope': 3283,
 'del': 2108,
 'bak': 1159,
 'long': 3957,
 'sum': 6204,
 'lucyxx': 4026,
 'eta': 2505,
 'taunton': 6326,
 '12': 269,
 'planned': 4929,
 'okday': 4635,
 'xx': 7183,
 'dont': 2280,
 'thnk': 6449,
 'wrong': 7156,
 'calling': 1538,
 'easy': 2383,
 'account': 774,
 'identification': 3385,
 'right': 5449,
 'nite': 4521,
 'pocay': 4967,
 'wocay': 7099,
 '4eva': 506,
 'promise': 5137,
 'ring': 5453,
 '2morrowxxxx': 394,
 'staff': 6046,
 'science': 5599,
 'nus': 4585,
 'edu': 2396,
 'sg': 5694,
 'phyhcmk': 4890,
 'teaching': 6344,
 'pc1323': 4825,
 'norm': 4549,
 '15': 292,
 'cos': 1914,
 'st': 6042,
 'tests': 6387,
 'sort': 5953,
 'library': 3860,
 'stuff': 6157,
 'point': 4975,
 'tomo': 6541,
 'letter': 3853,
 'access': 764,
 'til': 6485,
 'march': 4114,
 'better': 1268,
 'nt': 4572,
 'reasons': 5288,
 'bbd': 1204,
 'thts': 6469,
 'chikku': 1692,
 'hw': 3360,
 'abt': 755,
 'dvg': 2365,
 'cold': 1794,
 'heard': 3184,
 'tht': 6468,
 'vinobanagar': 6854,
 'violence': 6856,
 'condition': 1855,
 'ru': 5502,
 'problem': 5112,
 'amp': 916,
 'drive': 2326,
 'coherently': 1788,
 'flying': 2746,
 'monkeys': 4327,
 'wot': 7139,
 'certainly': 1625,
 'mind': 4241,
 'friend': 2835,
 'voda': 6870,
 'numbers': 4582,
 'ending': 2443,
 '7548': 613,
 'receive': 5297,
 'award': 1122,
 'match': 4137,
 'quoting': 5215,
 'code': 1786,
 '4041': 470,
 'standard': 6055,
 'rates': 5249,
 'app': 976,
 'purity': 5177,
 'friendship': 2837,
 'reading': 5270,
 'forwarded': 2797,
 'message': 4213,
 'seeing': 5640,
 'jay': 3577,
 'snickering': 5907,
 'tells': 6362,
 'totally': 6578,
 'fucking': 2859,
 'chords': 1715,
 'speak': 5984,
 'sony': 5941,
 'ericson': 2486,
 'der': 2139,
 'luks': 4027,
 'bt': 1467,
 'forgot': 2786,
 'modl': 4309,
 'mark': 4119,
 'works': 7127,
 'gets': 2940,
 'work': 7121,
 'yup': 7246,
 'izzit': 3553,
 'raining': 5226,
 'heavily': 3192,
 'mrt': 4364,
 'outside': 4721,
 'attend': 1084,
 'rounds': 5489,
 'reach': 5262,
 'yeah': 7205,
 'thought': 6455,
 'lemme': 3841,
 'goin': 2987,
 'later': 3795,
 'lil': 3881,
 'fever': 2664,
 'fine': 2696,
 'tap': 6315,
 'spile': 6004,
 'seven': 5684,
 'pub': 5166,
 'gas': 2901,
 'broad': 1444,
 'canal': 1550,
 'ok': 4633,
 'ask': 1051,
 'princess': 5097,
 'fuck': 2856,
 'yes': 7215,
 'thats': 6414,
 'cool': 1899,
 'liked': 3876,
 'photos': 4886,
 'lab': 3758,
 'goggles': 2985,
 'hurt': 3350,
 'tease': 6349,
 'life': 3866,
 'die': 2181,
 'plz': 4953,
 'rose': 5486,
 'grave': 3039,
 'stupid': 6161,
 'nice': 4503,
 'day': 2061,
 'bslvyl': 1463,
 'oz': 4743,
 'guy': 3089,
 'kinda': 3712,
 'flaky': 2719,
 'interested': 3490,
 'tonight': 6551,
 'possible': 5017,
 'ahmad': 861,
 'fren': 2825,
 'lor': 3972,
 '730': 608,
 'aiyah': 872,
 'wait': 6909,
 'entertain': 2467,
 'hee': 3195,
 'wesleys': 7020,
 'town': 6584,
 'bet': 1264,
 'does': 2257,
 'hella': 3203,
 'drugs': 2338,
 'havent': 3166,
 'stuck': 6149,
 'orchard': 4689,
 'dad': 2028,
 'car': 1563,
 'dinner': 2205,
 'leh': 3838,
 '400': 466,
 'xmas': 7179,
 'reward': 5438,
 'waiting': 6912,
 'computer': 1848,
 'randomly': 5243,
 'picked': 4895,
 'loyal': 4011,
 'mobile': 4298,
 'customers': 2016,
 '09066380611': 229,
 'haha': 3103,
 'officially': 4623,
 'paid': 4753,
 'market': 4120,
 '8th': 711,
 'free2day': 2815,
 'george': 2933,
 'pic': 4893,
 'jordan': 3627,
 '89080': 700,
 'wk': 7086,
 'saucy': 5577,
 'celeb': 1614,
 'pics': 4898,
 'pocketbabe': 4969,
 'uk': 6697,
 '0870241182716': 75,
 '1st': 327,
 'week': 6995,
 'no1': 4527,
 'tone': 6545,
 'mob': 4297,
 '8007': 634,
 'txting': 6676,
 'mates': 4141,
 'getzed': 2944,
 'pobox': 4958,
 '36504': 441,
 'w45wq': 6897,
 'norm150p': 4550,
 '16': 306,
 'lol': 3950,
 'guess': 3078,
 'jus': 3651,
 'blowing': 1331,
 'hair': 3106,
 'happy': 3142,
 'prince': 5095,
 'charming': 1652,
 'soon': 5944,
 'dun': 2356,
 'hard': 3143,
 'pick': 4894,
 'funny': 2872,
 'fact': 2592,
 'teaches': 6343,
 'volcanoes': 6876,
 'erupt': 2494,
 'tsunamis': 6647,
 'arise': 1019,
 'hurricanes': 3347,
 'sway': 6254,
 'aroundn': 1028,
 'choose': 1712,
 'natural': 4447,
 'disasters': 2219,
 'happens': 3138,
 'pls': 4947,
 'help': 3207,
 'sura': 6232,
 'expecting': 2558,
 'battery': 1199,
 'hont': 3278,
 'download': 2300,
 'movies': 4356,
 'thanks': 6407,
 'update_now': 6753,
 '12mths': 279,
 '400mins': 467,
 'mobileupd8': 4302,
 '08000839402': 44,
 'call2optout': 1528,
 'j5q': 3554,
 'hi': 3225,
 'cts': 1990,
 'employee': 2438,
 'hanging': 3128,
 'thread': 6458,
 'cause': 1603,
 'sec': 5626,
 'ericsson': 2487,
 'salesman': 5543,
 'shuhui': 5781,
 'quite': 5208,
 'gd': 2914,
 'use': 6780,
 'considering': 1874,
 'ultimately': 6700,
 'tor': 6568,
 'motive': 4348,
 'tui': 6653,
 'achieve': 779,
 'korli': 3741,
 'torch': 6569,
 '9ja': 729,
 'normal': 4551,
 'yunny': 7243,
 'walking': 6921,
 'citylink': 1730,
 'faster': 2628,
 'lecture': 3831,
 'dude': 2351,
 'buff': 1475,
 'wind': 7060,
 'cashbin': 1589,
 'lots': 3982,
 'cash': 1588,
 'weekend': 6996,
 'dear': 2072,
 'welcome': 7008,
 'biggest': 1283,
 'best': 1262,
 'away': 1124,
 'water': 6958,
 'logging': 3945,
 'desert': 2143,
 'geoenvironmental': 2932,
 'implications': 3415,
 'min': 4238,
 'voucher': 6883,
 'holder': 3260,
 'meal': 4166,
 'following': 2758,
 'link': 3895,
 'pc': 4824,
 'enjoy': 2456,
 'dining': 2204,
 'experiencehttp': 2562,
 'vouch4me': 6882,
 'etlp': 2507,
 'asp': 1059,
 'slowly': 5869,
 'clean': 1745,
 'heart': 3187,
 'blood': 1327,
 'miracle': 4256,
 'okie': 4638,
 'priest': 5093,
 'requirements': 5394,
 'bored': 1367,
 'depressed': 2136,
 'sittin': 5826,
 'waitin': 6911,
 'drops': 2333,
 'scary': 5593,
 'ugh': 6692,
 'leg': 3834,
 'hurts': 3352,
 'musta': 4404,
 'overdid': 4728,
 'mon': 4321,
 'sunday': 6212,
 'settled': 5682,
 'school': 5597,
 'wishin': 7076,
 'gr8': 3024,
 'outstanding': 4723,
 'commercial': 1822,
 'hasbro': 3153,
 'august': 1096,
 'jump': 3646,
 'hoops': 3281,
 'didn': 2178,
 'wrote': 7158,
 'times': 6488,
 'ritten': 5464,
 'let': 3851,
 'sit': 5822,
 'feeling': 2652,
 'angry': 932,
 'left': 3832,
 'wasn': 6947,
 'checked': 1667,
 'said': 5537,
 'sleep': 5851,
 'wouldn': 7143,
 'fold': 2752,
 'laundry': 3803,
 'bed': 1229,
 'friends': 2836,
 'valentines': 6805,
 'url': 6773,
 'dat': 2052,
 'oso': 4706,
 'oredi': 4693,
 'lar': 3786,
 'sad': 5532,
 'past': 4805,
 'morning': 4341,
 'hav': 3162,
 'newquay': 4496,
 'postcard': 5020,
 'gone': 2996,
 '1im': 323,
 'talkin': 6307,
 'bout': 1378,
 'wake': 6913,
 'tau': 6324,
 'sar': 5560,
 'piah': 4892,
 'hello': 3204,
 'damn': 2034,
 'christmas': 1720,
 'decided': 2083,
 'mp3': 4359,
 'doesnt': 2260,
 'opinion': 4675,
 'jada': 3561,
 'kusruthi': 3748,
 'lovable': 3993,
 'silent': 5799,
 'spl': 6010,
 'character': 1644,
 'matured': 4152,
 'stylish': 6165,
 'simple': 5804,
 'buns': 1484,
 'told': 6533,
 'adore': 814,
 'loverboy': 4000,
 'remember': 5356,
 'thank': 6406,
 'sister': 5820,
 'law': 3806,
 'meatballs': 4176,
 'grins': 3055,
 'babe': 1141,
 'rumour': 5514,
 'apartment': 966,
 'chennai': 1679,
 'sam': 5547,
 'eachother': 2369,
 '09066362231': 223,
 '07xxxxxxxxx': 39,
 '000': 1,
 'bonus': 1353,
 'caller': 1533,
 '02': 7,
 '06': 18,
 '03': 12,
 '2nd': 398,
 'attempt': 1082,
 'asap': 1044,
 'talking': 6308,
 'boy': 1396,
 'missing': 4268,
 'ah': 857,
 'den': 2123,
 'plus': 4951,
 'workin': 7124,
 'rite': 5463,
 'liao': 3857,
 'bahamas': 1157,
 'callfreefone': 1536,
 '08081560665': 55,
 'operator': 4674,
 'cruise': 1979,
 '2000': 337,
 '18': 311,
 '07786200117': 29,
 'number': 4581,
 'appointment': 985,
 'connect': 1868,
 'waheed': 6905,
 'fathima': 2632,
 'happen': 3133,
 'wow': 7145,
 'common': 1823,
 'freak': 2811,
 'unless': 6735,
 'chop': 1714,
 'hold': 3259,
 'connections': 1870,
 'maybe': 4160,
 'hour': 3305,
 'll': 3926,
 'mmmm': 4287,
 'fair': 2602,
 'weaknesses': 6975,
 'pushes': 5183,
 'knee': 3725,
 'exposes': 2572,
 'belly': 1251,
 'pulls': 5172,
 'head': 3173,
 'forget': 2781,
 'wicked': 7044,
 'smile': 5884,
 'defer': 2099,
 'admission': 812,
 'semester': 5653,
 '08718738034': 146,
 'toyota': 6586,
 'camry': 1548,
 'olayiwola': 4645,
 'mileage': 4231,
 'sell': 5649,
 'raise': 5227,
 'dough': 2299,
 'landing': 3774,
 'holla': 3264,
 'hot': 3300,
 'fantasies': 2619,
 '08707509020': 82,
 '20p': 346,
 'ntt': 4575,
 'po': 4956,
 'box': 1382,
 '1327': 282,
 'croydon': 1976,
 'cr9': 1943,
 '5wb': 555,
 '0870': 66,
 'dai': 2031,
 'downloaded': 2301,
 'exe': 2547,
 'file': 2681,
 'run': 5515,
 'installing': 3480,
 'strange': 6127,
 'sweet': 6258,
 'dreams': 2318,
 'dead': 2068,
 'geeeee': 2919,
 'barely': 1178,
 'stand': 6054,
 'actually': 796,
 'wat': 6952,
 'lect': 3830,
 '8077': 644,
 'tot': 6576,
 'ba': 1138,
 'gua': 3069,
 'mt': 4373,
 'faber': 2588,
 'yest': 7216,
 'mah': 4075,
 'feel': 2650,
 'night': 4511,
 '2day': 376,
 'collected': 1799,
 'sent': 5664,
 'control': 1889,
 'enufcredeit': 2476,
 'tocall': 6522,
 'shall': 5703,
 'ileave': 3399,
 'bus': 1493,
 'yor': 7225,
 'aight': 864,
 'safe': 5535,
 'trip': 6621,
 'panic': 4763,
 'surrender': 6241,
 'dirty': 2214,
 'fellow': 2657,
 'kallis': 3667,
 'ready': 5271,
 'bat': 1191,
 'innings': 3467,
 'rayan': 5253,
 'macleran': 4061,
 'getting': 2943,
 'food': 2765,
 'juz': 3657,
 'saw': 5583,
 'din': 2200,
 'somebody': 5929,
 'oic': 4630,
 'sis': 5819,
 'dunno': 2357,
 'eat': 2384,
 'sch': 5595,
 'alter': 900,
 '11': 261,
 'little': 3918,
 'party': 4796,
 'animal': 933,
 'buzz': 1506,
 'reminding': 5362,
 'loved': 3995,
 'naughty': 4449,
 'adoring': 815,
 'kiss': 3719,
 'checking': 1669,
 'thinl': 6444,
 'role': 5477,
 'sachin': 5529,
 'standing': 6056,
 'april': 996,
 'players': 4937,
 'allowed': 896,
 'leaving': 3829,
 'congrats': 1866,
 'plans': 4931,
 'oooh': 4665,
 'plenty': 4944,
 'request': 5390,
 'melle': 4191,
 'oru': 4703,
 'minnaminunginte': 4249,
 'nurungu': 4584,
 'vettam': 6836,
 'set': 5678,
 'callertune': 1535,
 'callers': 1534,
 'press': 5080,
 'copy': 1906,
 'lookin': 3964,
 'daytime': 2063,
 'fun': 2865,
 'wiv': 7085,
 'busty': 1498,
 'married': 4125,
 'chat': 1657,
 '09099726429': 243,
 'janinexx': 3569,
 'calls': 1539,
 'minmobsmorelkpobox177hp51fl': 4247,
 'schedule': 5596,
 'lk': 3925,
 'fyi': 2878,
 'taking': 6302,
 'quick': 5204,
 'shower': 5766,
 'epsilon': 2482,
 'quit': 5207,
 'minutes': 4254,
 'days': 2062,
 'satanic': 5569,
 'imposter': 3420,
 'pay': 4816,
 'destiny': 2154,
 'pray': 5055,
 'hopeso': 3288,
 'hunny': 3344,
 'amnow': 915,
 'feelin': 2651,
 'ill': 3400,
 'ithink': 3541,
 'tonsolitusaswell': 6555,
 'iam': 3364,
 'layin': 3808,
 'bedreal': 1231,
 'lotsof': 3984,
 'xxxx': 7187,
 'flower': 2740,
 'dippeditinadew': 2208,
 'lovingly': 4005,
 'touched': 6581,
 'itwhichturnedinto': 3544,
 'gifted': 2950,
 'tomeandsaid': 6540,
 '4u': 520,
 'woke': 7100,
 'looks': 3966,
 'scrumptious': 5616,
 'daddy': 2029,
 'wants': 6937,
 'chase': 1655,
 'crossing': 1974,
 'street': 6130,
 'abj': 749,
 'staying': 6080,
 'tones': 6546,
 'enjoyed': 2457,
 'content': 1882,
 '61610': 566,
 'unsubscribe': 6745,
 '08712400602450p': 95,
 'provided': 5156,
 'tones2you': 6548,
 'way': 6968,
 'bluff': 1336,
 'early': 2372,
 'jot': 3630,
 'things': 6437,
 'room': 5482,
 'lets': 3852,
 'esplanade': 2502,
 'giving': 2964,
 'lift': 3871,
 'pathaya': 4807,
 'enketa': 2460,
 'maraikara': 4112,
 'pa': 4744,
 'wan': 6929,
 'xy': 7191,
 'shop': 5748,
 'shopping': 5750,
 'auction': 1092,
 'round': 5487,
 'highest': 3230,
 'bid': 1279,
 '54': 544,
 'maximum': 4158,
 ...}

In [18]:
xtrain_transformed = vect.transform(xtrain)
xtest_transformed = vect.transform(xtest)

In [19]:
print(type(xtrain_transformed))
print(xtrain_transformed)

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 1564)	1
  (0, 2027)	1
  (0, 3785)	1
  (0, 3839)	1
  (0, 4148)	1
  (0, 7049)	1
  (1, 842)	1
  (1, 1031)	1
  (1, 1433)	1
  (1, 1532)	1
  (1, 1587)	1
  (1, 1695)	1
  (1, 1895)	1
  (1, 1898)	1
  (1, 2085)	1
  (1, 2898)	1
  (1, 3068)	2
  (1, 3308)	1
  (1, 3411)	1
  (1, 4018)	2
  (1, 4079)	1
  (1, 4095)	1
  (1, 4124)	1
  (1, 4396)	1
  (1, 4397)	1
  :	:
  (4174, 4289)	1
  (4174, 4492)	1
  (4174, 5627)	1
  (4174, 6300)	1
  (4174, 6909)	1
  (4174, 7206)	2
  (4175, 2552)	1
  (4175, 4341)	1
  (4175, 4901)	1
  (4175, 5851)	1
  (4175, 6592)	1
  (4175, 7062)	1
  (4176, 1031)	1
  (4176, 2061)	1
  (4176, 2351)	1
  (4176, 3014)	1
  (4176, 3078)	1
  (4176, 3652)	1
  (4176, 7222)	1
  (4177, 956)	1
  (4177, 2234)	1
  (4177, 3602)	1
  (4177, 5707)	1
  (4178, 2178)	1
  (4178, 4028)	1

In [20]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(xtrain_transformed, ytrain)

ypred_class = mnb.predict(xtest_transformed)

ypred_proba = mnb.predict_proba(xtest_transformed)

In [21]:
from sklearn.metrics import accuracy_score

accuracy_score(ytest,ypred_class)

0.9849246231155779

In [22]:
ypred_class

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [24]:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(ytest,ypred_class)

In [25]:
confusion

array([[1219,    8],
       [  13,  153]], dtype=int64)